In [1]:
# 图像ROI区域提取
import numpy as np
import cv2

img_color = cv2.imread(r'..\img\alphabet.jpg')
img_gray=cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
print(type(img_gray))   			#打印输出所读入图像的类型
cv2.rectangle(img_color,(160,140),(190,170),(0,0,255),3)  #openCV数组下标是[width，height，depth]
img_ROI=img_gray[140:170,160:190]       #numpy数组的下标是[height,width,depth]
cv2.imshow("color image",img_color)
cv2.waitKey(0)
cv2.imshow("ROI image",img_ROI)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>


In [ ]:
#numpy数组元素索引、切片
import numpy as np 
# a = np.arange(10)  #一维数组
# print(a[2:7:2])  
# print(a[::2])
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) #二维数组
print(a)

print (a[:,1])   # 第2列元素
# # print (a[1,...])   # 第2行元素
print (a[0,::2])  #
# # # print(a[0][1:]) 
print(a[1:3,1:3])

In [1]:
#numpy的下标是[z,y,x]
import numpy as np
a=np.array(np.arange(60))
b=a.reshape(3,4,5)
print(b)
print(b[1,0,2])
print(b.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
22
(3, 4, 5)


In [4]:
import numpy as np
import cv2

img_color = cv2.imread(r'.\img\1.png')
print(img_color.shape)
print(img_color)

(6, 6, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [183 183 183]
  [ 64  64  64]
  [159 159 159]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [ 24  24  24]
  [  0   0   0]
  [  8   8   8]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [255 255 255]
  [255 255 255]]]


In [ ]:
#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
#order的含义
a = np.array([[0, 1],[2, 3],[4, 5]]) 
b=np.reshape(a, (2, 3), order='F')
print(b)