In [1]:
import numpy as np
import scipy.signal as ss #引入scipy的signal模块

# 验证卷积定理
f=np.array([[8,1,6],[3,5,7],[4,9,2]])
g=np.array([[1,1,1],[1,1,1],[1,1,1]])
# 对两个离散序列进行扩展M=N=5
fe=np.zeros((5,5))    
ge=np.zeros((5,5)) 
fe[:3,:3]=f
ge[:3,:3]=g
#求扩展序列频域的乘积，再进行傅里叶反变换
temp=np.fft.fft2(fe)*np.fft.fft2(ge)
c=np.abs(np.fft.ifft2(temp))
c1=c[:5,:5] 
print('频域的乘积的傅里叶反变换=\n',c1)
#求空域的卷积
c=ss.convolve(fe,ge)
c2=c[:5,:5]
print('空域的卷积=\n',c2)



频域的乘积的傅里叶反变换=
 [[ 8.  9. 15.  7.  6.]
 [11. 17. 30. 19. 13.]
 [15. 30. 45. 30. 15.]
 [ 7. 21. 30. 23.  9.]
 [ 4. 13. 15. 11.  2.]]
空域的卷积=
 [[ 8.  9. 15.  7.  6.]
 [11. 17. 30. 19. 13.]
 [15. 30. 45. 30. 15.]
 [ 7. 21. 30. 23.  9.]
 [ 4. 13. 15. 11.  2.]]
